name: CI/CD

on:
  push:
    branches:
    - master
  pull_request:
jobs:
  lint:
    name: lint & check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
